ip: 0.0.0.0
port: 19132
defaultServer:
  port: 19133
  ip: 127.0.0.1
# Motd of this server
motd: §aProxProx §7Development Build
# The maximum number of players to play on this server
maxPlayers: 100
onlineMode: true
# Disable encryption? This does reduce the amount of CPU needed, also it seems to cause more stability
disableEncryption: false
# Gomint servers can use TCP listeners instead of Raknet to safe additional network delay and encryption overheads
useTCP: false