name: "Publish to maven central"

on:
  push:
    tags: [ "4.*" ]

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest
    name: Publish to maven central

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          check-latest: true
          distribution: 'zulu'

      - name: Setup gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Publish release to Sonatype
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USER: "${{ secrets.SONATYPE_USER }}"
          SONATYPE_TOKEN: "${{ secrets.SONATYPE_TOKEN }}"
          SIGNING_KEY: "${{ secrets.SIGNING_KEY }}"
          SIGNING_KEY_PASSWORD: "${{ secrets.SIGNING_KEY_PASSWORD }}"
