name: Validate target PR branch

on:
  pull_request:
    types: [ opened, edited ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v3
        with:
          target: release
          exclude: beta
